dataset: citeseer
# model
hidden_size: 64
layer_num: 2
activation: relu
dropout: 0.5
model: GNN
encoder: GCN_Encoder
# training
lr: 0.0005
weight_decay: 0.0005
epochs: 200
earlystop: True
patience: 20
